### ISSUE TITLE
How to establish communication with drones

### ISSUE THREAD

**Issue by xdwgood** [mit-acl/faster#14]
Hello developer!

Is there any documentation on how to communicate with mainstream flight controllers (eg:px4/ardupilot)?
thanks

**Comment by jtorde** [comment]
Hi @xdwgood!

[Taken partly from [here](https://github.com/mit-acl/aclswarm/issues/1)]

Any autopilot can be used as long as you can send position/velocity commands. The core code is autopilot agnostic. 

I would suggest writing your own node that subscribes to the /goal topic that MADER publishes (using snapdragon_msgs). Then, use mavros (or whatever) to relay the goal msg to the pixhawk. 

Hope this helps!

**Comment by xdwgood** [comment]
@jtorde  got it,thanks!
