### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by xdwgood** [mit-acl/faster#17]
hi developer!
when i try run `roslaunch faster faster.launch`

i got this error:

![Screenshot from 2020-12-10 13-14-53](https://user-images.githubusercontent.com/24932258/101724587-e5ac5700-3ae9-11eb-98ae-fb57eb687421.png)

@jtorde  could you help me?  

edit:
`roslaunch acl_sim start_world.launch
roslaunch acl_sim perfect_tracker_and_sim.launch
roslaunch global_mapper_ros global_mapper_node.launch
roslaunch faster faster_interface.launch
roslaunch faster faster.launch`

I can successfully run the first four commands

**Comment by xdwgood** [comment]
fixed

**Comment by yanmiao2** [comment]
@xdwgood Could you share how you fixed the problem?

**Comment by jtorde** [comment]
Hi @yanmiao2,

Could you check if Gurobi and its license are installed correctly? I.e., check the output of running `gurobi.sh` on the terminal. If installed correctly, it should launch the `Gurobi Interactive Shell`

**Comment by yanmiao2** [comment]
Yes, it's installed correctly. This issue "process has died" seems to happen randomly for me(Approximately 10% chance). But if I close the terminal and redo the command, everything seems fine. I'm not quite sure whether why it behaves this way.
