### ISSUE TITLE
NameError: global name 'QuadGoal' is not defined

### ISSUE THREAD

**Issue by DXSHAN-NEU** [mit-acl/faster#23]
Hi，I used faster on the ground robot，but there is such a mistake:

rospy.Subscriber("goal", QuadGoal, c.goalCB, queue_size=1)
NameError: global name 'QuadGoal' is not defined

Do you know the possible causes of this problem? Thanks a lot.

**Comment by jtorde** [comment]
Thank you, this bug was introduced last week after updating snapstack_msgs.
It should be fixed now in the last commit.
