### ISSUE TITLE
global_mapper_ros failed to reconstruct

### ISSUE THREAD

**Issue by cht649765744** [mit-acl/faster#25]
Hi, The "roslaunch global_mapper_ros global_mapper_node.launch" seems not work properly at my end.

![image](https://user-images.githubusercontent.com/39558579/112346240-c3eb7000-8c93-11eb-9adc-7a2d653a73ea.png)

One resulting effect is that after I run rviz, no occupancy grids are shown.

I checked the topic "/SQ01s/camera/depth/image_rect_raw" and the depth information has already been published there, which means the perfect_tracker_and_sim should be working properly.

The only evidence I catch in the terminal is a warning of the asynchronization in world_database_master_ros, but this warning does not persist (only appear at the beginning section of outputs)

Could you please help me to fix the global_mapper_ros? Thanks much!

**Comment by KingStrong-bit** [comment]
I meet the same question, have you solved this problem?
