### ISSUE TITLE
faster has died with GRBException

### ISSUE THREAD

**Issue by giorgiovaccarino** [mit-acl/faster#37]
Hello, during a simulated mission if I provide a waypoint beyond a wall I always get this error.
I have Gurobi version 9.12 installed on my system. Can this be a problem?

![Schermata da 2021-10-04 17-52-08](https://user-images.githubusercontent.com/25772255/135884193-52ff7f42-6da4-42fe-b1d4-9bfa7a6e1f7c.png)
![rviz_screenshot_2021_10_04-17_59_21](https://user-images.githubusercontent.com/25772255/135884483-e252f6ad-2cc9-446e-aac8-7f9ae30774c6.png)
![default_gzclient_camera(1)-2021-10-04T17_59_02 938044](https://user-images.githubusercontent.com/25772255/135884633-9ccf0b12-cdba-4388-8289-29fb819013d6.jpg)

**Comment by jtorde** [comment]
I am closing this, feel free to reopen if you are still facing this issue

**Comment by nvhungv2k** [comment]
@jtorde Pls reopen this issue, I also catch up it
My workspace: Ubuntu 18.04; ROS melodic; FASTER is on origin/master; Gurobi version version 9.1.0, build v9.1.0rc0
I meet this problem as soon as I run:
`$ roslaunch faster faster.launch`
![Uploading Screenshot from 2024-01-13 10-24-34.png…]()
