### ISSUE TITLE
How to run faster when the map is completely known?

### ISSUE THREAD

**Issue by YoungCapta1n** [mit-acl/faster#55]
Hi, I have read the paper about this trajectory planning algorithm. I'd like to figure out how to run the `faster` simulation in ros, when the map and obstacles are completely known. Is there any file or code need to be modified? Thanks for your time!

**Comment by jtorde** [comment]
Hi @YoungCapta1n,

You simply need to publish in the `global_mapper_ros/occupancy_grid` topic the sensor_msgs::PointCloud2 with the known map. and then the topic `global_mapper_ros/unknown_grid` should be an empty sensor_msgs::PointCloud2

Hope this helps
